### ISSUE TITLE
cannot reproduce the fast mlmodel

### ISSUE THREAD

**Issue by YingkunZhou** [Amshaker/SwiftFormer#3]
I download the mlmodel which mentioned in Readme and also use almost the same environment to convert pytorch model to mlmodel

- torch==1.10.1
- coremltools==5.2.0
- timm==0.5.4

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/43129850/232354925-f25da4cd-d9c5-492c-99bb-d2bb292e7444.png">
 
the left is mine, the right is downloaded from https://drive.google.com/file/d/1tZVxtbtAZoLLoDc5qqoUGulilksomLeK/view?usp=sharing

here is the layer distribution diff

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/43129850/232355338-b90e8875-e8d8-46d4-916c-2e52978dc4b8.png">

and here is the performance diff

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/43129850/232355353-1e6ebb93-dffd-4331-a1b2-2dfe9fe942c7.png">

- Xcode version is Version 14.3 (14E222b)
- test on M1 mini

**Comment by Amshaker** [comment]
Hi,

Please change this boolean "CoreMLConversion" in swiftformer.py to True before converting your model to mlmodel. The normalization layer is currently not supported by coreml and this boolean disables this layer. I raised an issue into coreml and hopefully they support it soon.

Please let me know if you still not be able to reproduce the same performance.

Best regards,
Abdelrahman.

**Comment by YingkunZhou** [comment]
oh I see, thanks.

**Comment by YingkunZhou** [comment]
But now the funny thing happens. When I change to coremltools==6.3.0, torch==2.0.0
![image](https://user-images.githubusercontent.com/43129850/232493873-8ac60663-df87-4150-9b48-af009520a170.png)
the left one is CoreMLConversion=False and the right one is CoreMLConversion=True
here is their performance diff
![image](https://user-images.githubusercontent.com/43129850/232494178-3ffdf613-d6d5-4d8d-be52-96f62538f4b8.png)
