### ISSUE TITLE
iphone12 vs iphone14

### ISSUE THREAD

**Issue by Feynman1999** [Amshaker/SwiftFormer#9]
Have you tried the latency on iPhone 12? thanks

**Comment by Amshaker** [comment]
Hi, No, we have not tried iPhone 12. 
We noticed that the reproduced numbers of the baseline & other methods on iPhone 14 are much faster compared to iPhone 12 (latency reported in their papers). It seems that the ANE of iPhone 14 and above versions is well optimized.
